global:
  configMapName: bankdev-configmap
  zipkinBaseURL: http://zipkin:9411/
  activeProfile: dev
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8761/eureka/