version: '3.8'

services:
  
  accounts:
    image: akramahammad/accounts:latest
    mem_limit: 700m
    ports: 
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: akramahammad/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  cards:
    image: akramahammad/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  configserver:
    image: akramahammad/config-server:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bank-network

networks:
  bank-network: